project:
  name: "Arbitron"
  version: "1.0.0"
  description: "Advanced Cryptocurrency Arbitrage Bot"

arbitrage:
  min_profit: 0.5
  pairs:
    - BTC/USDT
    - ETH/USDT
  exchanges:
    - binance
    - kraken
    - coinbase
    - kucoin
    - bybit
    - okx
database:
  url: postgresql://user:pass@postgres:5432/arbitron_db
redis:
  url: redis://redis:6379



risk_management:
  daily_profit_limit: 100  # Limite de lucro diário em USD
  daily_loss_limit: 50    # Limite de perda diária em USD

